# Generated by Django 3.1.7 on 2021-02-24 19:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='largeAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Add Name')),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.URLField(max_length=150, verbose_name='Preview LInk')),
            ],
            options={
                'verbose_name': 'Large AdSpace',
                'verbose_name_plural': 'Large AdSpace',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Magazine Issue Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tag_line', models.CharField(help_text='Magazine issue tag line', max_length=190, verbose_name='Tag line')),
                ('cover_image', models.ImageField(upload_to='images/', verbose_name='Cover Photo')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Magazine Issue Description')),
                ('issue_date', models.CharField(help_text='Example: July - May 2020', max_length=100, unique=True, verbose_name='Issue Date')),
                ('date', models.DateField(verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Magazine Issue',
                'verbose_name_plural': 'Magazine Issue',
            },
        ),
        migrations.CreateModel(
            name='smallAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Add Name')),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.URLField(max_length=150, verbose_name='Preview LInk')),
            ],
            options={
                'verbose_name': 'Small AdSpace',
                'verbose_name_plural': 'Small AdSpace',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Tag Description')),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='News Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/', verbose_name='News Cover Image')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Article Description')),
                ('body', ckeditor.fields.RichTextField(verbose_name='News Body')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Published or Draft', max_length=20, verbose_name='News Status')),
                ('news_feature', models.CharField(choices=[('main', 'Main'), ('featured', 'Featured')], help_text='News to be featured on home page', max_length=20, verbose_name='Article Feature')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag')),
            ],
            options={
                'verbose_name': 'News Updates',
                'verbose_name_plural': 'News Updates',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Image Name')),
                ('caption', models.CharField(max_length=100, verbose_name='Image Caption')),
                ('image', models.ImageField(upload_to='images/')),
                ('Tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag')),
            ],
            options={
                'verbose_name': 'Image Gallery',
                'verbose_name_plural': 'Image Gallery',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Article Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='', verbose_name='Cover Image')),
                ('article_feature', models.CharField(choices=[('main', 'Main'), ('featured', 'Featured')], max_length=20, verbose_name='Article Feature')),
                ('article_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Article Status')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Article Body')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('magazine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.magazine')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
