# Generated by Django 3.1.7 on 2021-03-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'News Updates', 'verbose_name_plural': 'News Updates'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='date',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='tag_line',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
